### ISSUE TITLE
Upgrade ModelMesh to v0.11

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/modelmesh-serving#169]
**Goal 1:** Upgrade ModelMesh serving in ODH and RHODS to upstream's v0.11
**Goal 2:** Resolve the clashing of ModelMesh and KServe CRDs --> if not resolved by Goal 1 automatically, a separate issue should follow up.

## Subtasks

- [x] Sync modelmesh repository(main branch) with upstream/main
- [x] Sync modelmesh-runtime-adapter repository(main branch) with upstream/main
- [x] Sync rest-proxy repository (main branch) with upstream/main
- [x] #175
- [x] #172
- [x] Create a new release branch from updated main branch 
- [x] #173
- [x] Update odh-manifest (fast image)
   - [x] #181  odh-manifests update in modelmesh-serving (to be later copied over separately to the correct branch in odh-manifests) 
- [x] Create modelmesh-serving PR to test OpenShift CI
  - [x] https://github.com/openshift/release/pull/43219
  - [x] https://github.com/openshift/release/pull/43096
- ~~[ ] Update Dockerfile.develop.ci/go.sum.develop/go.mod.develop repository for openshift-ci~~
- [ ] Update AutoMerger mapping for the created release branch

To do list from @VedantMahabaleshwarkar 
- [ ] Controller gen manifests will be in odh/modelmesh-serving/config/
   - [ ] main manifests dir is odh/modelmesh-serving/opendatahub/odh-manifests. So copy generated manifests from prev step into this directory
   - [ ] verify quickstart scripts work with new manifests

**Comment by vaibhavjainwiz** [comment]
template : https://github.com/opendatahub-io/modelmesh-serving/issues/122

**Comment by Jooho** [comment]
@vaibhavjainwiz @heyselbi @VedantMahabaleshwarkar  we only have 1 week for this task and I hope that it should be finished by end of the Tuesday. Then we can test it with an amount of time.

**Comment by heyselbi** [comment]
FVT CI tests are failing. The pods are crashlooping, unsure why yet. I am missing access to openshift org - requested it today. Vedant is currently trying to look into it without access to the CI cluster.

**Comment by heyselbi** [comment]
**Update from JooHo:** 

- modelmesh serving images were built for fast/stable(v0.11.0)
- modelmesh/modelmesh-runtime-adapter/rest-proxy failed fvt because it used a wrong modelmesh-serving-develop (This [openshift ci pr](https://github.com/openshift/release/pull/43449) will solve this issue)
- I expect other images will be done by 1pm today.

**Comment by heyselbi** [comment]
Follow up: transition to RHODS: https://github.com/opendatahub-io/modelmesh-serving/issues/228
