### ISSUE TITLE
Upgrade MM to v0.11.0 in RHODS + Metrics hotfix

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/modelmesh-serving#228]
Tasks for odh/modelmesh-serving repo and all related repos to it.
- [x] Step 1a: Sync main with v0.11.1 (includes thorough testing of it BEFORE merging) in all MM repos
- [x] Step 1b: Create 0.11.1 branches in all MM repos
- [ ] Step 1c: Update version file in all MM repos (ie. https://github.com/opendatahub-io/rest-proxy/blob/release-0.11.1/version)
- [ ] Step 1d: Create v0.11.1 tags in all MM repos
- [x] Step 1e: Update openshift-ci to point to correct branches
- [x] Step 2: Cherry pick the relevant commit from main to v0.11.0 branch in ODH - report as a hotfix (includes thorough testing of it BEFORE merging)
- [x] Step 3: Downstream v0.11.0 (that includes the hotfix) to RHODS
- [x] Step 4: Update necessary tags, if needed

**Comment by heyselbi** [comment]
OpenShift-CI config PRs: 
https://github.com/openshift/release/pull/44249
https://github.com/openshift/release/pull/44252

**Comment by bdattoma** [comment]
@heyselbi could you share more about the metrics hotfix? what is the issue?

**Comment by Jooho** [comment]
@bdattoma it is about this pr(https://github.com/opendatahub-io/modelmesh/pull/40)
This change is in release 0.11.1 upstream and we already sync it into odh 0.11.1 release branch. This 0.11.1 will be incubating in ODH 1.11 However, we got a request to put this change into 1.35 so we put this as a hotfix into 0.11.0(rhods 1.35)
if you have any further questions, please let me know.
